include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
    no_wildcard_variable_uses: true

analyzer:
  errors:
    avoid_print: warning
    no_wildcard_variable_uses: warning
